### ISSUE TITLE
Issues when testing with the meta-operator

### ISSUE THREAD

**Issue by horis233** [IBM/ibm-commonui-operator#11]
1. issue in CSV
in 
```
      - description: CommonWebUI is the Schema for the commonwebuis API
        displayName: CommonWebUI service
        kind: CommonWebUI
        name: commonwebuis.operators.ibm.com
        version: v1alpha1
      - description: LegacyHeader is the Schema for the legacyHeader API
        displayName: LegacyHeader service
        kind: LegacyHeader
        name: legacyheaders.operators.ibm.com
        version: v1alpha1
      - description: >-
          NavConfiguration for the CommonWebUI service which returns custom nav
          configurations
        displayName: NavConfiguration service
        kind: NavConfiguration
        name: navconfiguration.foundation.ibm.com  <- miss `s` 
        version: v1
```

  `name: navconfiguration.foundation.ibm.com`  ->  `name: navconfigurations.foundation.ibm.com`

2. `REPLACE_IMAGE` in the Operator pod
```
   - resources: {}
      terminationMessagePath: /dev/termination-log
      name: common-webui
      command:
        - common-webui
      env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: 'metadata.annotations[''olm.targetNamespaces'']'
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: common-webui
      securityContext:
        capabilities:
          drop:
            - KILL
            - MKNOD
            - SETGID
            - SETUID
        runAsUser: 1000590000
      imagePullPolicy: Always
      volumeMounts:
        - name: common-webui-token-bpvfm
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: REPLACE_IMAGE
```

3. package name is not consistent in [commonui-operator](https://github.com/IBM/ibm-commonui-operator/blob/master/deploy/olm-catalog/ibm-commonui-operator/ibm-commonui-operator.package.yaml#L5) and [meta-operator](https://github.com/IBM/meta-operator/blob/master/deploy/crds/operator.ibm.com_v1alpha1_metaoperatorcatalog_cr.yaml#L52)
/cc @ericabr
